/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yalantis_ucrop_task_BitmapCropTask */

#ifndef _Included_com_yalantis_ucrop_task_BitmapCropTask
#define _Included_com_yalantis_ucrop_task_BitmapCropTask
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_yalantis_ucrop_task_BitmapCropTask
* Method:    cropCImg
* Signature: (Ljava/lang/String;Ljava/lang/String;IIIIF)Z
*/
JNIEXPORT jboolean JNICALL Java_com_yalantis_ucrop_task_BitmapCropTask_cropCImg
(JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jfloat, jfloat, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
